# Generated by Django 4.2.7 on 2024-01-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="themes",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Opponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sex", models.CharField(max_length=1)),
                ("name", models.CharField(max_length=255)),
                ("anniversary_details", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "opponents",
            },
        ),
        migrations.CreateModel(
            name="AnniversaryRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("relationships", models.CharField(max_length=255)),
                ("purpose", models.CharField(max_length=255)),
                ("present", models.CharField(max_length=255)),
                ("present_type", models.CharField(max_length=255)),
                ("range_of_amounts", models.CharField(max_length=255)),
                (
                    "amount_of_money",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("photo", models.ImageField(upload_to="photos/")),
                ("memories", models.TextField()),
                ("self_assessment", models.TextField()),
                ("improvements", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boards.opponent",
                    ),
                ),
            ],
            options={
                "db_table": "anniversary_records",
            },
        ),
    ]
