# Generated by Django 4.2.7 on 2024-03-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_alter_comments_id_alter_themes_id_opponent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="opponent",
            name="sex",
            field=models.CharField(choices=[("M", "男性"), ("F", "女性")], max_length=1),
        ),
        migrations.AlterField(
            model_name="anniversaryrecords",
            name="present_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boards.presenttype",
            ),
        ),
    ]
